# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c506fec685efe47b5e2297e14a1aed67de4887613526e2de8287646d0164cb5a5b3852ca0ced81ad892c037f30a9098628590bb7f1ff2e2cae5857f3efeda569

test:
  secret_key_base: aa3e24d43ef39ecbe04e02ef73022ac7b9dac4f752b0828186fd9a2d69cb42ccb3abeb9132447e8c34b27940dcff49795fad2af0b297da5f18666027559dfc8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
